/**
 * Deploy AGA Donation Contract to BNB Smart Chain
 * This script deploys the donation contract that auto-forwards all funds to admin wallet
 */

const { ethers } = require('ethers');
const fs = require('fs');
const path = require('path');
require('dotenv').config();

// Contract ABI and Bytecode (generated after compiling the Solidity contract)
// Note: In production, you would compile the .sol file using hardhat or foundry
// For now, we'll use the ABI for the deployed contract
const DONATION_CONTRACT_ABI = [
    "constructor(address payable _adminWallet)",
    "function donate(string memory geniusId, string memory message, bool isAnonymous) external payable returns (bytes32)",
    "function getDonation(bytes32 donationId) external view returns (address donor, string memory geniusId, uint256 amount, uint256 timestamp, string memory message, bool isAnonymous)",
    "function getGeniusTotalDonations(string memory geniusId) external view returns (uint256)",
    "function getGeniusDonationCount(string memory geniusId) external view returns (uint256)",
    "function getTotalDonationsCount() external view returns (uint256)",
    "function updateAdminWallet(address payable newAdminWallet) external",
    "function getContractBalance() external view returns (uint256)",
    "function adminWallet() external view returns (address)",
    "function owner() external view returns (address)",
    "event DonationReceived(bytes32 indexed donationId, address indexed donor, string indexed geniusId, uint256 amount, uint256 timestamp, bool isAnonymous)",
    "event DonationForwarded(bytes32 indexed donationId, address indexed adminWallet, uint256 amount)",
    "event AdminWalletUpdated(address indexed oldWallet, address indexed newWallet)"
];

async function deployContract() {
    console.log('🚀 Deploying AGA Donation Contract...\n');

    // Validate environment variables
    const adminWallet = process.env.DONATION_ADMIN_WALLET;
    const deployerPrivateKey = process.env.DONATION_DEPLOYER_PRIVATE_KEY;
    const network = process.env.BNB_NETWORK || 'testnet';

    if (!adminWallet) {
        throw new Error('DONATION_ADMIN_WALLET not found in .env. Run generateAdminWallet.js first.');
    }

    if (!deployerPrivateKey) {
        throw new Error('DONATION_DEPLOYER_PRIVATE_KEY not found in .env. Run generateAdminWallet.js first.');
    }

    // Validate admin wallet address
    if (!ethers.isAddress(adminWallet)) {
        throw new Error('Invalid admin wallet address');
    }

    // Network configuration
    const networkConfig = {
        testnet: {
            rpcUrl: process.env.BNB_TESTNET_RPC || 'https://data-seed-prebsc-1-s1.binance.org:8545/',
            chainId: 97,
            name: 'BNB Smart Chain Testnet',
            explorer: 'https://testnet.bscscan.com'
        },
        mainnet: {
            rpcUrl: process.env.BNB_MAINNET_RPC || 'https://bsc-dataseed.binance.org/',
            chainId: 56,
            name: 'BNB Smart Chain Mainnet',
            explorer: 'https://bscscan.com'
        }
    };

    const config = networkConfig[network];
    console.log(`📡 Connecting to ${config.name}...`);
    console.log(`   RPC: ${config.rpcUrl}\n`);

    // Connect to network
    const provider = new ethers.JsonRpcProvider(config.rpcUrl);
    const deployer = new ethers.Wallet(deployerPrivateKey, provider);

    console.log(`💼 Deployer Address: ${deployer.address}`);

    // Check deployer balance
    const balance = await provider.getBalance(deployer.address);
    const balanceInBNB = ethers.formatEther(balance);
    console.log(`💰 Deployer Balance: ${balanceInBNB} BNB\n`);

    if (parseFloat(balanceInBNB) < 0.01) {
        console.warn('⚠️  WARNING: Low BNB balance. You may need more BNB for gas fees.');
        console.warn(`   Get testnet BNB from: https://testnet.binance.org/faucet-smart\n`);
    }

    console.log(`🎯 Admin Wallet (will receive all donations): ${adminWallet}\n`);

    // Note: To actually deploy, you would need the contract bytecode
    // This is typically generated by compiling the Solidity contract
    // For now, we'll create a mock deployment record and instructions

    console.log('━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━');
    console.log('⚠️  DEPLOYMENT INSTRUCTIONS');
    console.log('━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n');

    console.log('To deploy the contract, you need to compile it first:');
    console.log('');
    console.log('Option 1: Using Hardhat');
    console.log('  1. Install Hardhat: npm install --save-dev hardhat');
    console.log('  2. Initialize: npx hardhat init');
    console.log('  3. Move DonationContract.sol to contracts/ folder');
    console.log('  4. Compile: npx hardhat compile');
    console.log('  5. Deploy: npx hardhat run scripts/deploy.js --network bnbTestnet');
    console.log('');
    console.log('Option 2: Using Remix IDE (Easiest)');
    console.log('  1. Go to https://remix.ethereum.org');
    console.log('  2. Create new file: DonationContract.sol');
    console.log('  3. Paste the contract code from backend/contracts/DonationContract.sol');
    console.log('  4. Compile (Ctrl+S)');
    console.log('  5. Deploy tab → Environment: Injected Provider - MetaMask');
    console.log('  6. Constructor arg: ' + adminWallet);
    console.log('  7. Click Deploy');
    console.log('');
    console.log('Option 3: Using Foundry');
    console.log('  1. Install Foundry: curl -L https://foundry.paradigm.xyz | bash');
    console.log('  2. Initialize: forge init');
    console.log('  3. Move DonationContract.sol to src/ folder');
    console.log('  4. Deploy: forge create --rpc-url ' + config.rpcUrl + ' \\');
    console.log('             --private-key $DONATION_DEPLOYER_PRIVATE_KEY \\');
    console.log('             --constructor-args ' + adminWallet + ' \\');
    console.log('             src/DonationContract.sol:AGADonationContract');
    console.log('');

    // Create deployment record template
    const deploymentRecord = {
        network: config.name,
        chainId: config.chainId,
        adminWallet: adminWallet,
        deployerAddress: deployer.address,
        deployedAt: null, // To be filled after actual deployment
        contractAddress: null, // To be filled after actual deployment
        transactionHash: null, // To be filled after actual deployment
        abi: DONATION_CONTRACT_ABI,
        instructions: 'Contract must be compiled and deployed using Hardhat, Remix, or Foundry',
        status: 'pending'
    };

    const deploymentDir = path.join(__dirname, '..', 'secure');
    if (!fs.existsSync(deploymentDir)) {
        fs.mkdirSync(deploymentDir, { recursive: true });
    }

    const recordPath = path.join(deploymentDir, 'donation-contract-deployment.json');
    fs.writeFileSync(recordPath, JSON.stringify(deploymentRecord, null, 2));

    console.log('━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n');
    console.log(`📝 Deployment record template saved to: ${recordPath}`);
    console.log('   Update this file with the actual contract address after deployment\n');

    console.log('✅ Next Steps:');
    console.log('   1. Choose a deployment method (Remix recommended for quick start)');
    console.log('   2. Deploy the contract with admin wallet as constructor argument');
    console.log('   3. Update donation-contract-deployment.json with contract address');
    console.log('   4. Add DONATION_CONTRACT_ADDRESS to your .env file');
    console.log('   5. Verify contract on BSCScan (optional but recommended)\n');

    return deploymentRecord;
}

// Run the script
if (require.main === module) {
    deployContract()
        .then(() => {
            console.log('✅ Deployment preparation complete!\n');
            process.exit(0);
        })
        .catch(error => {
            console.error('❌ Error:', error.message);
            process.exit(1);
        });
}

module.exports = { deployContract };
